baseURL = "https://fossmarks.org/"
languageCode = "en-us"
title = "FOSSmarks"
theme = "minimal"
disqusShortname = "fossmarks" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Weston Davis"
    description = "A practical guide to understanding trademarks in the context of Free and Open Source Software projects."
    githubUsername = "FOSSmarks"
    accent = "#2980B9"
    showBorder = true
    backgroundColor = "white"
    font = "Open Sans" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "The Guide"
    weight = 3

[[menu.main]]
    url = "/contributors/"
    name = "Contributors"
    weight = 4

[[menu.main]]
    url = "/seekadvice/"
    name = "Seek Advice"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.


[[menu.icon]]
    url = "https://github.com/FOSSmarks/FOSSmarks"
    name = "github"
    weight = 1
